// <auto-generated />
using System;
using BrekkieBeacon.Infrastructure;
using FelineFeeder.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FelineFeeder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218000156_AddInstructions")]
    partial class AddInstructions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BrekkieBeacon.Core.FeedingTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedingTimes");
                });

            modelBuilder.Entity("BrekkieBeacon.Core.FeedingTime", b =>
                {
                    b.OwnsOne("BrekkieBeacon.Core.LEDInstructions", "LEDInstructions", b1 =>
                        {
                            b1.Property<Guid>("FeedingTimeId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Brightness")
                                .HasColumnType("REAL");

                            b1.HasKey("FeedingTimeId");

                            b1.ToTable("FeedingTimes");

                            b1.WithOwner()
                                .HasForeignKey("FeedingTimeId");
                        });

                    b.OwnsOne("BrekkieBeacon.Core.MotorInstructions", "MotorInstructions", b1 =>
                        {
                            b1.Property<Guid>("FeedingTimeId")
                                .HasColumnType("TEXT");

                            b1.Property<uint>("Steps")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("WaitBetweenSteps")
                                .HasColumnType("TEXT");

                            b1.HasKey("FeedingTimeId");

                            b1.ToTable("FeedingTimes");

                            b1.WithOwner()
                                .HasForeignKey("FeedingTimeId");
                        });

                    b.Navigation("LEDInstructions")
                        .IsRequired();

                    b.Navigation("MotorInstructions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
