// <auto-generated />
using System;
using BrekkieBeacon.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrekkieBeacon.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224175427_AddFeedingTimeIsEnabled")]
    partial class AddFeedingTimeIsEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BrekkieBeacon.Core.FeedingTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FeedingTimes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79809983-9993-4b93-941e-32363198084b"),
                            IsEnabled = true,
                            Name = "🌅 Morning Morsel",
                            Time = new TimeOnly(5, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("79809983-9993-4b93-941e-32363198084e"),
                            IsEnabled = true,
                            Name = "☀️ Breakfast Banquet",
                            Time = new TimeOnly(5, 15, 0)
                        },
                        new
                        {
                            Id = new Guid("a392764b-d291-4940-9e11-22964177013c"),
                            IsEnabled = true,
                            Name = "🌇 Sunset Snack",
                            Time = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("a392764b-d291-4940-9e11-22964177013d"),
                            IsEnabled = true,
                            Name = "🌙 Dinner Delight",
                            Time = new TimeOnly(17, 15, 0)
                        });
                });

            modelBuilder.Entity("BrekkieBeacon.Core.FeedingTime", b =>
                {
                    b.OwnsOne("BrekkieBeacon.Core.LEDInstructions", "LEDInstructions", b1 =>
                        {
                            b1.Property<Guid>("FeedingTimeId")
                                .HasColumnType("TEXT");

                            b1.Property<float>("Brightness")
                                .HasColumnType("REAL");

                            b1.HasKey("FeedingTimeId");

                            b1.ToTable("FeedingTimes");

                            b1.WithOwner()
                                .HasForeignKey("FeedingTimeId");

                            b1.HasData(
                                new
                                {
                                    FeedingTimeId = new Guid("79809983-9993-4b93-941e-32363198084b"),
                                    Brightness = 1f
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("79809983-9993-4b93-941e-32363198084e"),
                                    Brightness = 1f
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("a392764b-d291-4940-9e11-22964177013c"),
                                    Brightness = 1f
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("a392764b-d291-4940-9e11-22964177013d"),
                                    Brightness = 1f
                                });
                        });

                    b.OwnsOne("BrekkieBeacon.Core.MotorInstructions", "MotorInstructions", b1 =>
                        {
                            b1.Property<Guid>("FeedingTimeId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("NegateDirection")
                                .HasColumnType("INTEGER");

                            b1.Property<uint>("Steps")
                                .HasColumnType("INTEGER");

                            b1.Property<TimeSpan>("WaitBetweenSteps")
                                .HasColumnType("TEXT");

                            b1.HasKey("FeedingTimeId");

                            b1.ToTable("FeedingTimes");

                            b1.WithOwner()
                                .HasForeignKey("FeedingTimeId");

                            b1.HasData(
                                new
                                {
                                    FeedingTimeId = new Guid("79809983-9993-4b93-941e-32363198084b"),
                                    NegateDirection = false,
                                    Steps = 1450u,
                                    WaitBetweenSteps = new TimeSpan(0, 0, 0, 0, 5)
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("79809983-9993-4b93-941e-32363198084e"),
                                    NegateDirection = false,
                                    Steps = 1450u,
                                    WaitBetweenSteps = new TimeSpan(0, 0, 0, 0, 5)
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("a392764b-d291-4940-9e11-22964177013c"),
                                    NegateDirection = false,
                                    Steps = 1450u,
                                    WaitBetweenSteps = new TimeSpan(0, 0, 0, 0, 5)
                                },
                                new
                                {
                                    FeedingTimeId = new Guid("a392764b-d291-4940-9e11-22964177013d"),
                                    NegateDirection = false,
                                    Steps = 1450u,
                                    WaitBetweenSteps = new TimeSpan(0, 0, 0, 0, 5)
                                });
                        });

                    b.Navigation("LEDInstructions")
                        .IsRequired();

                    b.Navigation("MotorInstructions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
